export const FERTILIZER_SOIL_OPTIONS = [
  'Acidic Soil',
  'Alkaline Soil',
  'Loamy Soil',
  'Neutral Soil',
  'Peaty Soil',
];

export const FERTILIZER_CROP_OPTIONS = [
  'Adzuki Beans',
  'Apple',
  'Banana',
  'Black Gram',
  'Chickpea',
  'Cotton',
  'Grapes',
  'Ground Nut',
  'Kidney Beans',
  'Lentil',
  'Maize',
  'Mango',
  'Millet',
  'Moth Beans',
  'Mung Bean',
  'Muskmelon',
  'Orange',
  'Papaya',
  'Peas',
  'Pigeon Peas',
  'Pomegranate',
  'Rice',
  'Sugarcane',
  'Tobacco',
  'Watermelon',
  'Wheat',
];
